### ISSUE TITLE
pip3 giving this error

### ISSUE THREAD

**Issue by svennela** [srid99/einthusan-dl#20]
./einthusan-dl
Traceback (most recent call last):
  File "./einthusan-dl", line 4, in <module>
    from einthusan import einthusan_dl
  File "/Users/localhost/einthusan-dl/einthusan/einthusan_dl.py", line 20, in <module>
    import requests
ImportError: No module named requests

**Comment by srid99** [comment]
Since you are using pip3, can you try running it with python3 ?

Eg: `python3 einthusan-dl <url>`

Let me know if it does the job.

**Comment by srid99** [comment]
@svennela reopen the issue in case if the above solution doesn't work
